project_id = "qzasxqikcrvvxuptgvdd"

[functions.helius-webhook]
verify_jwt = false

[functions.smartsupp-webhook]
verify_jwt = false

[functions.tawkto-webhook]
verify_jwt = false

[functions.chat-send-message]
verify_jwt = false

[functions.telegram-bot-webhook]
verify_jwt = false

[functions.setup-telegram-webhook]
verify_jwt = false

[functions.chat-get-messages]
verify_jwt = false

[functions.worker-bot-webhook]
verify_jwt = false

[functions.setup-worker-bot-webhook]
verify_jwt = false

[functions.generate-logo]
verify_jwt = false

[functions.track-visit]
verify_jwt = false

[functions.check-dns]
verify_jwt = false